#pragma once

#include "PrimitiveTypes.h"

namespace NetworkLib
{
	enum class ErrorCode : uint16
	{
		SUCCESS = 0,

		CONFIG_FILE_NOT_FOUND = 100,
		CONFIG_FILE_PARSE_ERROR = 101,

		WSA_START_UP_FAIL = 300,
		CREATE_EVENT_FAIL = 301,
		IO_CONTEXT_POOL_CREATE_FAIL = 302,
		IO_CONTEXT_ELEMENT_IS_NOT_ENOUGH = 303,

		SOCKET_INIT_FAIL = 400,
		SOCKET_BIND_FAIL = 401,
		SOCKET_LISTEN_FAIL = 402,
		SOCKET_INIT_REUSE_ADDR_FAIL = 403,
		SOCKET_ACCEPT_ASYNC_FAIL = 404,

		CLIENT_SESSION_NOT_EXIST = 500,
		CLIENT_SESSION_NOT_CONNECTED = 501,
		CLIENT_SESSION_RECEIVE_FAIL = 502,
		CLIENT_SESSION_RECEIVE_BUFFER_FULL = 503,
		CLIENT_SESSION__RECEIVE_MAX_PACKET_SIZE = 504,
		CLIENT_SESSION_SEND_FAIL = 505,
		CLIENT_SESSION_SEND_BUFFER_FULL = 506,
		CLIENT_SESSION_LOCK_FAIL = 507,
	

		CLIENT_SESSION_MANAGER_INIT_FAIL = 600,
		CLIENT_SESSION_MANAGER_INDEX_ALIGN_FAIL = 601,
	};
}
